//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_subjects
    {
        public int student_no { get; set; }
        public string subjects_code { get; set; }
        public Nullable<double> midterm { get; set; }
        public Nullable<double> final { get; set; }
        public Nullable<double> resit { get; set; }
        public Nullable<double> avg { get; set; }
        public int id { get; set; }
        public string year { get; set; }
    
        public virtual students students { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
